### ISSUE TITLE
Add searx for various search engines?

### ISSUE THREAD

**Issue by NintendoManiac64** [dybdeskarphet/privacy-redirector#13]
For example, the following userscript by someone else redirects bing to searx:

- https://greasyfork.org/scripts/423346-bing-to-searx

So what about integrating something like that, but for not just Bing but also DuckDuckGo, Google, Yahoo, Yandex, etc?

**Comment by dybdeskarphet** [comment]
We can't choose to use the FOSS front-end for a particular site without a redirection tool but I think search engines are an exception because you can set a default search engine and use it without dealing with another search engine, considering that people rarely share a search engine URL with each other. 

I'll keep this issue open and add the Searx redirection if it's not too complex to implement.

**Comment by NintendoManiac64** [comment]
I mean, you already have support for farside, and searx is indeed something that farside includes.

**Comment by dybdeskarphet** [comment]
Yes indeed, what I meant by implementing was the differences between search parameters and other subpages, sorry for the confusion.
